services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: content-stats-app
    command: uvicorn app.main:my_app --host 0.0.0.0 --port 8001 --reload
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    restart: always
    # environment:
    #   - OPENAI_API_KEY=<not set>
